[mysql]
# 数据库服务器地址
hostName = "127.0.0.1"
# 数据库服务器端口
hostPort = "3306"
# 数据库名
database = "test"
# 数据库用户名
userName = "root"
# 数据库密码
password = "123456"
# 数据库编码
charset = "utf8mb4"

# 数组
[[test]]
TestBool = true
testName = "laixhe"
testAge = 18
# 数组
like = ["动漫","搬砖"]
TestArrayInt = [1,2,8,9]

[[test]]
testName = "laiki"
testAge = 19
like = ["搬砖","code"]
TestFloat = 1.123456
