[package]
name = "axum-demo"
version = "0.1.0"
authors = ["laixhe <laixhe@laixhe.com>"]
edition = "2021"

[dependencies]
# 异步
tokio = { version = "1.0", features = ["full"] }
# web
axum = "0.7"
axum-extra = "0.9"
axum-macros = "0.4"
http = "1.0"
tower = "0.4"
tower-http = "0.5"
# 序列化
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
# 日志
tracing = "0.1"
tracing-subscriber = "0.3"
# 时间
chrono = {version = "0.4",features=["serde"]}
time = "0.3"
# JWT
jsonwebtoken = "9"
# 错误 error
anyhow = "1.0"
# 数据库
sqlx = { version = "0.8", features = [ "runtime-tokio", "tls-rustls", "mysql", "chrono" ] }
# 参数(表单)验证
validator = { version = "0.18", features = ["derive"] }

#[dev-dependencies]

