[tool.poetry]
name = "pylog"
version = "0.1.0"
description = ""
authors = ["laiki <laiki@laixhe.com>"]
readme = "README.md"
packages = [{include = "pylog"}]

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
