[package]
name = "actix-web-demo"
version = "0.1.0"
authors = ["laiki <535250340@qq.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
actix-web = "3"
diesel = { version = "1.4.6", features = ["sqlite", "r2d2"] }
anyhow = "1.0"
chrono = "0.4"